language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
virtualenv:
    system_site_packages: true
before_install:
 - sudo apt-get install -qq python-numpy python-scipy python-matplotlib python-h5py
# command to install dependencies
install:
  - "pip install -r requirements.txt --use-mirrors"
# command to run tests
script: py.test
